# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('exam_room', models.CharField(max_length=20)),
                ('office', models.CharField(max_length=20)),
                ('scheduled_time', models.DateTimeField(auto_now_add=True)),
                ('checkin_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('', ''), ('Checked In', 'Checked In')], default='', max_length=20, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
