# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20190224_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
