# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20190301_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('', ''), ('Checked In', 'Checked In'), ('In Session', 'In Session'), ('Complete', 'Complete')], default='', max_length=20, null=True),
        ),
    ]
