# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20190225_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checkin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
