# Generated by Django 2.1.7 on 2019-02-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20190225_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
