# Generated by Django 2.1.7 on 2019-02-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20190226_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checkin_time',
            field=models.DateTimeField(null=True),
        ),
    ]
