# Generated by Django 2.1.7 on 2019-02-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20190227_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='exam_room',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='office',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('', ''), ('Checked In', 'Checked In')], default='', max_length=20, null=True),
        ),
    ]
