# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-03 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_waiting_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='waiting_time',
            new_name='session_time',
        ),
    ]
