# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-04 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20190303_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('', ''), ('Checked In', 'Checked In'), ('In Session', 'In Session'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='', max_length=20, null=True),
        ),
    ]
