# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='social_security_number',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
